#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

BACKUP_FILE_PREFIX="backup-omv"

purgeOld()
{
    # get number of days to keep
    keep=$(omv_config_get "/config/system/backup/keep")
    if [[ ${keep} -gt 0 ]]; then
        echo "Purging old files..."
        find "${backupDir}" -maxdepth 1 -type f -mtime ${keep} -name "${BACKUP_FILE_PREFIX}*" -delete
        echo "Purging done."
    else
        echo "Purging disabled."
    fi
}

# date
date=$(date +"%d-%b-%Y_%H-%M-%S")

# clean apt-get cache to save space
apt-get clean

# clean openmediavault upload cache and recreate Packages file
rm -f /var/cache/openmediavault/archives/*
touch /var/cache/openmediavault/archives/Packages

# Get the shared folder reference and path
sfref=$(omv_config_get "/config/system/backup/sharedfolderref")
if ! omv_isuuid "${sfref}" ]; then
    echo "No backup volume set.  Please choose a backup volume."
    exit 1
fi
sfpath="$(omv_get_sharedfolder_path "${sfref}")"
if [ ! -d "${sfpath}" ]; then
    echo "Shared folder directory does not exist.  Exiting..."
    exit 1
fi

# set backup directory and create it if it doesn't exist
backupDir="${sfpath}/omvbackup"
mkdir -p ${backupDir}

# Get the method of backup
method=$(omv_config_get "/config/system/backup/method")
echo "Method: ${method}"

# get device file for /
devicefile=$(awk '$5 == "/" { print $10 }' /proc/self/mountinfo)
echo "Device file:  ${devicefile}"

if [ -z "${devicefile}" ]; then
    echo "Could not determine root device file.  Exiting..."
    exit 1
fi

# get root device
root=$(omv_config_get "/config/system/backup/root")

# if root is empty, try to determine root device
if [ -z "${root}" ]; then
    root="/dev/$(lsblk -no pkname ${devicefile})"
fi
echo "Root drive: ${root}"

if [ -z "${root}" ]; then
    echo "Could not determine root device.  Exiting..."
    exit 1
fi

# save helpful information
fdisk -l ${root} > "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.fdisk"
blkid > "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.blkid"
dpkg -l | grep openmediavault > "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.packages"

# save partition table and mbr
dd if=${root} of="${backupDir}/${BACKUP_FILE_PREFIX}-${date}.grub" bs=446 count=1
dd if=${root} of="${backupDir}/${BACKUP_FILE_PREFIX}-${date}.grubparts" bs=512 count=1

# perform backup based on method selected
case ${method} in
    dd)
        echo "Using dd..."
        dd if=${devicefile} bs=1M conv=sync,noerror status=progress | gzip -c > "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.dd.gz"
        sync
        purgeOld
        ;;

    fsarchiver)
        echo "Using FSArchiver..."
        passwd="$(omv_config_get "/config/system/backup/passwd")"
        password=""
        if [ -n "${passwd}" ]; then
            echo "Encrypting archive..."
            password="--cryptpass=${passwd} "
        fi
        fsarchiver savefs ${password}-o "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.fsa" ${devicefile} -v -A
        purgeOld
        fsarchiver archinfo ${password} "${backupDir}/${BACKUP_FILE_PREFIX}-${date}.fsa"
        ;;

    rsync)
        echo "Using rsync..."
        extra=$(omv_config_get "/config/system/backup/extraoptions")

        rsync -aAXvxx /* "${backupDir}/" \
            --delete \
            --exclude=/dev \
            --exclude=/proc \
            --exclude=/sys \
            --exclude=/tmp \
            --exclude=/run \
            --exclude=/mnt \
            --exclude=/media \
            --exclude=/lost+found \
            --exclude=/export \
            --exclude=/home/ftp \
            --exclude=/srv ${extra}
        ;;
esac

exit 0
