#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ISO_PATH="/boot"
GRUB_CLONEZILLA="/etc/grub.d/42_clonezilla"
CLONEZILLA_VERSION="2.2.3-25"
CLONEZILLA_ISO="clonezilla-live-${CLONEZILLA_VERSION}-i686-pae.iso"

GRUB_SYSRESCCD="/etc/grub.d/42_sysresccd"
SYSRESCCD_VERSION="4.2.0"
SYSRESCCD_ISO="systemrescuecd-x86-${SYSRESCCD_VERSION}.iso"

GRUB="/etc/default/grub"
GRUB_BACKUP="grub.bak"
TFILE="/tmp/grub"

backup()
{
    BACKUP_PATH=$(omv_config_get "//system/backup/path")
    SYSDRIVE_UUID="$(cat /etc/fstab | egrep "UUID.* / " | awk '{print $1}' | sed 's/UUID=//g')"
    SYSDRIVE="$(ls -l /dev/disk/by-uuid/ | grep $SYSDRIVE_UUID | awk '{print $11}' | sed 's/..\/..\///g')"

    # clean apt-get cache to save space
    apt-get clean

    # clean openmediavault upload cache and recreate Packages file
    rm -f /var/cache/openmediavault/archives/*
    touch /var/cache/openmediavault/archives/Packages

    # check to see if backup path exists and backup
    if [ "${BACKUP_PATH}" != "" ]; then

        if [ -d "${BACKUP_PATH}" ]; then
            mkdir -p ${BACKUP_PATH}
        fi

        rsync -aAXv /* ${BACKUP_PATH} --delete \
            --exclude=/dev \
            --exclude=/proc \
            --exclude=/sys \
            --exclude=/tmp \
            --exclude=/run \
            --exclude=/mnt \
            --exclude=/media \
            --exclude=/lost+found \
            --exclude=/export \
            --exclude=/home/ftp \
            --exclude=/srv/ftp \
            --exclude=/srv/tftp

        dd if=/dev/${SYSDRIVE} of=${BACKUP_PATH}/grub.dd bs=446 count=1
        dd if=/dev/${SYSDRIVE} of=${BACKUP_PATH}/grub_parts.dd bs=512 count=1
        blkid > ${BACKUP_PATH}/uuids
    else
        echo "No backup volume set.  Please choose a backup volume."
    fi
}

installclonezilla()
{
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        rm -f ${ISO_PATH}/clonezilla*.iso
        wget "https://downloads.sourceforge.net/project/clonezilla/clonezilla_live_stable/${CLONEZILLA_VERSION}/${CLONEZILLA_ISO}" -O ${ISO_PATH}/${CLONEZILLA_ISO}
    fi

    cat <<EOF > ${GRUB_CLONEZILLA}
#!/bin/sh
exec tail -n +3 \$0
menuentry "Clonezilla Live" {
  set isofile="${ISO_PATH}/${CLONEZILLA_ISO}"
  loopback loop \$isofile
  linux (loop)/live/vmlinuz boot=live live-config noswap nolocales edd=on nomodeset ocs_live_run="ocs-live-general" ocs_live_extra_param="" keyboard-layouts="" ocs_live_batch="no" locales="" ocs_daemonon="ssh" vga=788 nosplash toram=filesystem.squashfs findiso=\$isofile
  initrd (loop)/live/initrd.img
}
EOF

    chmod 755 ${GRUB_CLONEZILLA}
    update-grub
}

installsysresccd()
{
    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        rm -f ${ISO_PATH}/systemrescuecd*.iso
        wget "https://sourceforge.net/projects/systemrescuecd/files/sysresccd-x86/${SYSRESCCD_VERSION}/${SYSRESCCD_ISO}/download" -O ${ISO_PATH}/${SYSRESCCD_ISO}
    fi

    cat <<EOF > ${GRUB_SYSRESCCD}
#!/bin/sh
exec tail -n +3 \$0
menuentry "SystemRescueCD" {
  set isofile="${ISO_PATH}/${SYSRESCCD_ISO}"
  loopback loop \$isofile
  linux (loop)/isolinux/rescue32 nomodeset rootpass=openmediavault isoloop=\$isofile
  initrd (loop)/isolinux/initram.igz
}
EOF

    chmod 755 ${GRUB_SYSRESCCD}
    update-grub
}

rebootclonezilla()
{

    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        echo "Please click on Install button."
    else
        NEW="GRUB_DEFAULT=saved"
        DEFAULT=$(cat /etc/default/grub | grep GRUB_DEFAULT | cut -d= -f2)
        ENTRY=$(($(cat /boot/grub/grub.cfg | grep menuentry | grep -n Clonezilla | cut -f1 -d:)-1))

        echo "Configuring grub to boot once from Clonezilla iso..."

        sed "s/GRUB_DEFAULT=.*/$NEW/g" ${GRUB} > ${TFILE} && mv ${TFILE} ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootsysresccd()
{

    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        echo "Please click on Install button."
    else
        NEW="GRUB_DEFAULT=saved"
        DEFAULT=$(cat /etc/default/grub | grep GRUB_DEFAULT | cut -d= -f2)
        ENTRY=$(($(cat /boot/grub/grub.cfg | grep menuentry | grep -n SystemRescueCD | cut -f1 -d:)-1))

        echo "Configuring grub to boot once from SystemRescueCD iso..."

        sed "s/GRUB_DEFAULT=.*/$NEW/g" ${GRUB} > ${TFILE} && mv ${TFILE} ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootomv()
{
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        echo "Please click on Install button."
    else
        NEW="GRUB_DEFAULT=0"

        echo "Configuring grub to boot OpenMediaVault by default..."

        sed "s/GRUB_DEFAULT=.*/$NEW/g" ${GRUB} > ${TFILE} && mv ${TFILE} ${GRUB}
        grub-set-default 0
        update-grub
        grub-reboot 0
    fi
}

case $2 in
    backup)
        backup
    ;;

    install)
        installclonezilla
    ;;

    installsys)
        installsysresccd
    ;;

    clonezilla)
        rebootclonezilla
    ;;

    sysresccd)
        rebootsysresccd
    ;;

    omv)
        rebootomv
    ;;

esac

exit 0
