#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# clean apt-get cache to save space
apt-get clean

# clean openmediavault upload cache and recreate Packages file
rm -f /var/cache/openmediavault/archives/*
touch /var/cache/openmediavault/archives/Packages

# Get the shared folder reference and path
sfref=$(omv_config_get "/config/system/backup/sharedfolderref")

# check to see if backup path exists and backup
if [ "${sfref}" != "" ]; then
    sfpath=$(omv_get_sharedfolder_path "${sfref}")

    rsync -aAXv /* ${sfpath} \
        --delete \
        --exclude=/dev \
        --exclude=/proc \
        --exclude=/sys \
        --exclude=/tmp \
        --exclude=/run \
        --exclude=/mnt \
        --exclude=/media \
        --exclude=/lost+found \
        --exclude=/export \
        --exclude=/home/ftp \
        --exclude=/srv/ftp \
        --exclude=/srv/tftp

    SYSDRIVE_UUID="$(cat /etc/fstab | egrep "UUID.* / " | awk '{print $1}' | sed 's/UUID=//g')"
    SYSDRIVE="$(ls -l /dev/disk/by-uuid/ | grep $SYSDRIVE_UUID | awk '{print $11}' | sed 's/..\/..\///g')"

    dd if=/dev/${SYSDRIVE} of=${sfpath}/grub.dd bs=446 count=1
    dd if=/dev/${SYSDRIVE} of=${sfpath}/grub_parts.dd bs=512 count=1
    blkid > ${sfpath}/uuids
    dpkg -l | grep openmediavault > ${sfpath}/packages
else
    echo "No backup volume set.  Please choose a backup volume."
fi

exit 0
