#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # Variables
        omv_set_default "OMV_BACKUP_DIR_NAME" "omvbackup" false
        omv_set_default "OMV_BACKUP_FILE_PREFIX" "backup-omv" false
        omv_set_default "OMV_BACKUP_MAX_DEPTH" "1" false
        omv_set_default "OMV_BACKUP_FSA_COMP_LEVEL" "2" false
        omv_set_default "OMV_BACKUP_ZSTD_OPTIONS" "" false
        omv_set_default "OMV_BACKUP_ZSTD_ADAPT" "0" false

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.system.backup"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.system.backup" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
