#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! omv_config_exists "/config/system/backup"; then
            echo "Initial configuration."
            object="<mntentref>0</mntentref>"
            omv_config_add_element "/config/system" "backup" "${object}" true
        fi

        ;;
        
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
