#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions



case "$1" in
    configure)
        SERVICE_XPATH_NAME="backup"
        SERVICE_XPATH="/config/system/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/system" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "sharedfolderref" ""
        fi

        if omv_config_exists "${SERVICE_XPATH}/path"; then
            omv_config_delete "${SERVICE_XPATH}/path"
        fi

        if omv_config_exists "${SERVICE_XPATH}/mntentref"; then
            mntentref="$(omv_config_get "${SERVICE_XPATH}/mntentref")"
            echo "copying"
            omv_config_add_element "${SERVICE_XPATH}" "sharedfolderref" "${mntentref}"
            omv_config_delete "${SERVICE_XPATH}/mntentref"
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
