#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    # Activate trigger to purge cached files.
    dpkg-trigger update-fixperms
}

case "$1" in
    purge)
        # remove any scheduled jobs created by plugin
        XPATH="/config/system/crontab/job"
        xmlstarlet sel -t -m "${XPATH}" -v "uuid" -n ${OMV_CONFIG_FILE} | xmlstarlet unesc |
          while read uuid; do
            cmd=$(omv_config_get "${XPATH}[uuid='${uuid}']/command")
            if [ "${cmd}" = "/usr/sbin/omv-backup" ]; then
              echo "delete ${uuid}..."
              omv_config_delete "${XPATH}[uuid='${uuid}']"
            fi
          done
        omv-salt deploy run --quiet cron || :

        remove_action
        echo "Cleaning up configuration database ..."
        omv_config_delete "/config/system/backup"
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
