#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

GRUB_CLONEZILLA="/etc/grub.d/42_clonezilla"
ISO_PATH="/boot"

case "$1" in
    remove)
        rm -f ${GRUB_CLONEZILLA}
        rm -f ${ISO_PATH}/clonezilla*.iso
        rm -f ${ISO_PATH}/systemrescue*.iso
        omv-mkconf backup omv
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
