#!/bin/sh

. /usr/share/openmediavault/scripts/helper-functions

if ! omv_config_exists "//system/crontab/job[uuid='32664b22-5a9d-11ec-8834-6f00f75b23ee']"; then
  echo "Adding backup plugin cron task..."
  object="<uuid>32664b22-5a9d-11ec-8834-6f00f75b23ee</uuid>"
  object="${object}<enable>0</enable>"
  object="${object}<execution>exactly</execution>"
  object="${object}<sendemail>0</sendemail>"
  object="${object}<comment></comment>"
  object="${object}<type>userdefined</type>"
  object="${object}<minute>30</minute>"
  object="${object}<everynminute>0</everynminute>"
  object="${object}<hour>1</hour>"
  object="${object}<everynhour>0</everynhour>"
  object="${object}<month>*</month>"
  object="${object}<dayofmonth>*</dayofmonth>"
  object="${object}<everyndayofmonth>0</everyndayofmonth>"
  object="${object}<dayofweek>7</dayofweek>"
  object="${object}<username>root</username>"
  object="${object}<command>/usr/sbin/omv-backup</command>"
  omv_config_add_node_data "//system/crontab" "job" "${object}"
else
  echo "Backup plugin cron task already exists!"
fi

exit 0
